# Generated by Django 3.2.25 on 2024-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='no_of_base_jumps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
