# Generated by Django 3.2.25 on 2024-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('coordinates', models.FloatField()),
                ('rock_drop', models.IntegerField()),
                ('total_height', models.IntegerField()),
                ('access', models.CharField(max_length=250)),
                ('cliff_aspect', models.CharField(max_length=3)),
                ('opened_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='../default_post_qpihoy', upload_to='images/')),
            ],
        ),
    ]
