# Generated by Django 3.2.4 on 2024-11-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20241106_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='total_height',
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_qpihoy', null=True, upload_to='images/'),
        ),
    ]
