# Generated by Django 3.2.4 on 2024-11-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20241106_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='rock_drop',
            field=models.IntegerField(null=True),
        ),
    ]
