# Generated by Django 3.2.4 on 2024-11-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_total_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='access',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='cliff_aspect',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
