# Generated by Django 3.2.4 on 2024-11-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20241107_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dz02qubd3/image/upload/v1729441727/default_post_qpihoy.jpg', null=True),
        ),
    ]
